before_script:
    - git --version

ps_build:
  stage: build
  script:
    - .\build.ps1 -target "CI-Build"
  artifacts:
    paths:
      - coverage/
  coverage: '/Line coverage: (\d+\.\d+\%)/'
  tags:
    - powershell
    - windows
    - mssql

pages:
  stage: deploy
  dependencies:
    - ps_build
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master