before_script:
    - git --version

ps_build:
  stage: build
  script:
    - .\build.ps1 -target "CI-Build"
  artifacts:
    paths:
      - ./*-test-result.xml
    reports:
      junit: 
        - ./*-test-result.xml
    expire_in: 30 days
  coverage: '/Unit line coverage: (\d+\.\d+\%)/'
  tags:
    - powershell
    - windows
    - mssql
